/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "MemoryMapping.h"
#include "Buzzer.h"
#include "Fuel.h"
#include "HeadAndParkingLights.h"
#include "Indicators.h"
#include "USART.h"

uint8_t  g_count1, g_count2, g_count3;
uint32_t g_result;
uint32_t FUEL_LEVEL_INDICATOR;
uint8_t  DUTY_CYCLE = 0;
int  g_res;
char g_character = 'j';
char g_message;


void delay()
{
	for(uint32_t i = 0 ; i < 300000; i++);
}

int main()
{
	GPIOConfiguration();
	USARTInit();
	Fuel();

	uint32_t IGNITION_SWITCH, RIGHT_INDICATOR_SWITCH, LEFT_INDICATOR_SWITCH, HEAD_LIGHT_SWITCH;

//	RCC->AHB1ENR |=  (7<<0);

	GPIOB->ODR   |= ( 1 << 13);
	GPIOB->ODR   |= ( 1 << 14);
	GPIOB->ODR   |= ( 1 << 15);
	GPIOC->ODR   |= ( 1 << 6);

	while(1)
	{
		TIM1->CCR2 = (uint32_t) TIM1->ARR * 0/100;
		TIM1->CCR3 = (uint32_t) TIM1->ARR * 0/100;
		TIM1->CCR3 = (uint32_t) TIM1->ARR * 0/100;

		RIGHT_INDICATOR_SWITCH = (uint8_t)(GPIOB->IDR & (1<<7));    // sw1
		IGNITION_SWITCH        = (uint8_t)(GPIOB->IDR & (1<<3));    //sw2
		LEFT_INDICATOR_SWITCH  = (uint8_t)(GPIOB->IDR  & (1<<4));   //sw3
		HEAD_LIGHT_SWITCH      = (uint16_t)(GPIOA->IDR  & (1<<15)); //sw4

		//To turn  on the PB 13 LED
		//TID30
		if(IGNITION_SWITCH == 0)
		{
			GPIOB->ODR &= ~( 1 << 13);

			delay();

			while(1)
			{
				ADC1->CR2 |=(1<<30);// ENABLE conversion of channels
				while(!(ADC1->SR & 2));
				g_result = (uint32_t)(ADC1->DR);

				FUEL_LEVEL_INDICATOR  = (g_result>>6);

				USARTWrite(g_character);
				g_message = USARTRead();

				RIGHT_INDICATOR_SWITCH = (uint8_t)(GPIOB->IDR & (1<<7)); //SWITCH1
				IGNITION_SWITCH        = (uint8_t)(GPIOB->IDR & (1<<3)); //SWITCH2
				LEFT_INDICATOR_SWITCH  = (uint8_t)(GPIOB->IDR & (1<<4)); //SWITCH3
				HEAD_LIGHT_SWITCH      = (uint16_t)(GPIOA->IDR & (1<<15)); //SWITCH4

				TIM3->CCR1 = (uint32_t) TIM3->ARR * DUTY_CYCLE/100;

				//TO TURN OFF EVERYTHING
				//TID40
				if(IGNITION_SWITCH == 0)
				{
					GPIOC->ODR &= ~(1 << 6);
					delay();

					GPIOB->ODR |= (1 << 13);
					delay();

					TIM1->CCR2  = (uint32_t) TIM1->ARR * 0/100;
					delay();

					TIM1->CCR3  = (uint32_t) TIM1->ARR * 0/100;
					delay();

					BuzzerOFF();
					delay();

					break;
				}


			    /*When switch 1 is pressed the led is switched on along with buzzer of duty cycle 50%*/
				//TID80
				if(RIGHT_INDICATOR_SWITCH == 0 && g_count2==0)
				{
					g_count1++;
					RightIndicator();
					TIM1->CCR2 = (uint32_t) TIM1->ARR * 50/100; // 50% duty cycle for PWM
					BuzzerON();

					//TID90
					if(g_count1 == 2)
					{
						TIM1->CCR2 = (uint32_t) TIM1->ARR * 0/100;
						BuzzerOFF();
						g_count1   = 0;
					}
				}

				/*When switch 3 is pressed the led is switched on along with buzzer of duty cycle 50%*/
				//TID100
				if(LEFT_INDICATOR_SWITCH == 0 && g_count1==0)
				{
					g_count2++;
					LeftIndicator();
					TIM1->CCR3 = (uint32_t) TIM1->ARR * 50/100; // 50% duty cycle for PWM
					BuzzerON();

					//TID110
					if(g_count2 == 2)
					{
						TIM1->CCR3 = (uint32_t) TIM1->ARR * 0/100;
						BuzzerOFF();
						g_count2=0;
					}
				}


				/*WHEN HEAD_LIGHT_SWITCH IS PRESSED FIRST:
				LED IS SWITCHED ON WITH 10 % INTENSITY
				WHEN HEAD_LIGHT_SWITCH IS PRESSED SECOND TIME :
				LED IS SWITCHED ON WITH 90 % INTENSITY
				WHEN HEAD_LIGHT_SWITCH IS PRESSED THIRD TIME:
				BOTH THE INDICATORS ARE SWITCHED ON TOGETHER*/
				if(HEAD_LIGHT_SWITCH == 0 && g_count1==0 && g_count2==0)
				{
					g_count3++;

					//TID120
					if(g_count3 == 1)
					{
						DUTY_CYCLE = 90;
					}

					//TID130
					if(g_count3 == 2)
					{
						DUTY_CYCLE = 10;
					}

					//TID140
					if(g_count3 == 3)
					{
						LeftIndicator();
						TIM1->CCR3 = (uint32_t) TIM1->ARR * 50/100;

						RightIndicator();
						TIM1->CCR2 = (uint32_t) TIM1->ARR * 50/100;

						BuzzerON();
						TIM3->CCR4 = (uint32_t) TIM3->ARR * 50/100;
					}

					//TID150
					if(g_count3 == 4)
					{
						DUTY_CYCLE = 100;
						delay();
						TIM1->CCR2 = (uint32_t) TIM1->ARR * 0/100;
						TIM1->CCR3 = (uint32_t) TIM1->ARR * 0/100;
						BuzzerOFF();
						g_count3 = 0;
					}

					HeadAndParkingLights();
					delay();
				}
			}
		}
	}

	return 0;
}
